/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 at Tue May 16 20:21:31 2023. */

#include "addressbook.pb.hpp"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(tutorial_Person, tutorial_Person, AUTO)


PB_BIND(tutorial_Person_PhoneNumber, tutorial_Person_PhoneNumber, AUTO)


PB_BIND(tutorial_AddressBook, tutorial_AddressBook, AUTO)




