/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 at Tue May 16 20:21:31 2023. */

#ifndef PB_SENSOR_IMU_PB_HPP_INCLUDED
#define PB_SENSOR_IMU_PB_HPP_INCLUDED
#include <pb.h>
#include "timestamp.pb.hpp"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _sensor_Vector3d {
    double x;
    double y;
    double z;
} sensor_Vector3d;

typedef struct _sensor_IMU {
    bool has_time;
    google_protobuf_Timestamp time;
    bool has_acceleration;
    sensor_Vector3d acceleration;
    bool has_angular_velocity;
    sensor_Vector3d angular_velocity;
    bool has_magnetic;
    sensor_Vector3d magnetic;
} sensor_IMU;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define sensor_Vector3d_init_default             {0, 0, 0}
#define sensor_IMU_init_default                  {false, google_protobuf_Timestamp_init_default, false, sensor_Vector3d_init_default, false, sensor_Vector3d_init_default, false, sensor_Vector3d_init_default}
#define sensor_Vector3d_init_zero                {0, 0, 0}
#define sensor_IMU_init_zero                     {false, google_protobuf_Timestamp_init_zero, false, sensor_Vector3d_init_zero, false, sensor_Vector3d_init_zero, false, sensor_Vector3d_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define sensor_Vector3d_x_tag                    1
#define sensor_Vector3d_y_tag                    2
#define sensor_Vector3d_z_tag                    3
#define sensor_IMU_time_tag                      1
#define sensor_IMU_acceleration_tag              2
#define sensor_IMU_angular_velocity_tag          3
#define sensor_IMU_magnetic_tag                  4

/* Struct field encoding specification for nanopb */
#define sensor_Vector3d_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   x,                 1) \
X(a, STATIC,   SINGULAR, DOUBLE,   y,                 2) \
X(a, STATIC,   SINGULAR, DOUBLE,   z,                 3)
#define sensor_Vector3d_CALLBACK NULL
#define sensor_Vector3d_DEFAULT NULL

#define sensor_IMU_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  time,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  acceleration,      2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  angular_velocity,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  magnetic,          4)
#define sensor_IMU_CALLBACK NULL
#define sensor_IMU_DEFAULT NULL
#define sensor_IMU_time_MSGTYPE google_protobuf_Timestamp
#define sensor_IMU_acceleration_MSGTYPE sensor_Vector3d
#define sensor_IMU_angular_velocity_MSGTYPE sensor_Vector3d
#define sensor_IMU_magnetic_MSGTYPE sensor_Vector3d

extern const pb_msgdesc_t sensor_Vector3d_msg;
extern const pb_msgdesc_t sensor_IMU_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sensor_Vector3d_fields &sensor_Vector3d_msg
#define sensor_IMU_fields &sensor_IMU_msg

/* Maximum encoded size of messages (where known) */
#define sensor_IMU_size                          111
#define sensor_Vector3d_size                     27

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
