/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 at Tue May 16 20:21:31 2023. */

#include "sample.pb.hpp"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sample_SampleRequest, sample_SampleRequest, AUTO)


PB_BIND(sample_SampleResponse, sample_SampleResponse, AUTO)


PB_BIND(sample_Sample, sample_Sample, AUTO)


PB_BIND(sample_Sample_SampleMapEntry, sample_Sample_SampleMapEntry, AUTO)




