/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 at Tue May 16 20:21:31 2023. */

#ifndef PB_SAMPLE_SAMPLE_PB_HPP_INCLUDED
#define PB_SAMPLE_SAMPLE_PB_HPP_INCLUDED
#include <pb.h>
#include "timestamp.pb.hpp"
#include "duration.pb.hpp"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 列挙型 */
typedef enum _sample_Sample_SampleEnum {
    sample_Sample_SampleEnum_UNKNOWN = 0,
    sample_Sample_SampleEnum_TEST1 = 1,
    sample_Sample_SampleEnum_TEST2 = 2,
    sample_Sample_SampleEnum_TEST3 = 3
} sample_Sample_SampleEnum;

/* Struct definitions */
typedef struct _sample_SampleRequest {
    pb_callback_t name;
} sample_SampleRequest;

/* メッセージ型
 右の数字は「タグナンバー」 */
typedef struct _sample_Sample {
    /* スカラー型
 数値、文字列、真偽値、バイト配列がある */
    int32_t id;
    pb_callback_t name;
    bool isBool;
    /* deprecated 廃止予定かつ非推奨であるフィールドを明示する */
    pb_callback_t duplicated_field;
    /* マップ（連想配列） */
    pb_callback_t sample_map;
    /* Well Known Types */
    bool has_sample_duration;
    google_protobuf_Duration sample_duration;
    bool has_create_time;
    google_protobuf_Timestamp create_time;
} sample_Sample;

typedef struct _sample_SampleResponse {
    bool has_sample;
    sample_Sample sample;
} sample_SampleResponse;

typedef struct _sample_Sample_SampleMapEntry {
    pb_callback_t key;
    pb_callback_t value;
} sample_Sample_SampleMapEntry;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _sample_Sample_SampleEnum_MIN sample_Sample_SampleEnum_UNKNOWN
#define _sample_Sample_SampleEnum_MAX sample_Sample_SampleEnum_TEST3
#define _sample_Sample_SampleEnum_ARRAYSIZE ((sample_Sample_SampleEnum)(sample_Sample_SampleEnum_TEST3+1))






/* Initializer values for message structs */
#define sample_SampleRequest_init_default        {{{NULL}, NULL}}
#define sample_SampleResponse_init_default       {false, sample_Sample_init_default}
#define sample_Sample_init_default               {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_Duration_init_default, false, google_protobuf_Timestamp_init_default}
#define sample_Sample_SampleMapEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define sample_SampleRequest_init_zero           {{{NULL}, NULL}}
#define sample_SampleResponse_init_zero          {false, sample_Sample_init_zero}
#define sample_Sample_init_zero                  {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_Duration_init_zero, false, google_protobuf_Timestamp_init_zero}
#define sample_Sample_SampleMapEntry_init_zero   {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define sample_SampleRequest_name_tag            1
#define sample_Sample_id_tag                     1
#define sample_Sample_name_tag                   2
#define sample_Sample_isBool_tag                 3
#define sample_Sample_duplicated_field_tag       4
#define sample_Sample_sample_map_tag             6
#define sample_Sample_sample_duration_tag        9
#define sample_Sample_create_time_tag            13
#define sample_SampleResponse_sample_tag         1
#define sample_Sample_SampleMapEntry_key_tag     1
#define sample_Sample_SampleMapEntry_value_tag   2

/* Struct field encoding specification for nanopb */
#define sample_SampleRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1)
#define sample_SampleRequest_CALLBACK pb_default_field_callback
#define sample_SampleRequest_DEFAULT NULL

#define sample_SampleResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sample,            1)
#define sample_SampleResponse_CALLBACK NULL
#define sample_SampleResponse_DEFAULT NULL
#define sample_SampleResponse_sample_MSGTYPE sample_Sample

#define sample_Sample_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, BOOL,     isBool,            3) \
X(a, CALLBACK, SINGULAR, STRING,   duplicated_field,   4) \
X(a, CALLBACK, REPEATED, MESSAGE,  sample_map,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sample_duration,   9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  create_time,      13)
#define sample_Sample_CALLBACK pb_default_field_callback
#define sample_Sample_DEFAULT NULL
#define sample_Sample_sample_map_MSGTYPE sample_Sample_SampleMapEntry
#define sample_Sample_sample_duration_MSGTYPE google_protobuf_Duration
#define sample_Sample_create_time_MSGTYPE google_protobuf_Timestamp

#define sample_Sample_SampleMapEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define sample_Sample_SampleMapEntry_CALLBACK pb_default_field_callback
#define sample_Sample_SampleMapEntry_DEFAULT NULL

extern const pb_msgdesc_t sample_SampleRequest_msg;
extern const pb_msgdesc_t sample_SampleResponse_msg;
extern const pb_msgdesc_t sample_Sample_msg;
extern const pb_msgdesc_t sample_Sample_SampleMapEntry_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sample_SampleRequest_fields &sample_SampleRequest_msg
#define sample_SampleResponse_fields &sample_SampleResponse_msg
#define sample_Sample_fields &sample_Sample_msg
#define sample_Sample_SampleMapEntry_fields &sample_Sample_SampleMapEntry_msg

/* Maximum encoded size of messages (where known) */
/* sample_SampleRequest_size depends on runtime parameters */
/* sample_SampleResponse_size depends on runtime parameters */
/* sample_Sample_size depends on runtime parameters */
/* sample_Sample_SampleMapEntry_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
